import BuildServerProtocol
import LanguageServerProtocol

struct PublishDiagnosticsNotification: BSPNotification {
    static let method: String = "build/publishDiagnostics"

    /// The document where the diagnostics are published
    var textDocument: BuildServerProtocol.TextDocumentIdentifier

    /// The build target where the diagnostics origin.
    /// It is valid for one text document to belong to multiple
    /// build targets, for example sources that are compiled against multiple
    /// platforms (JVM, JavaScript).
    var buildTarget: BuildTargetIdentifier

    /// A unique identifier generated by the client to identify this request.
    var originId: String?

    /// The diagnostics to be published by the client
    var diagnostics: [Diagnostic]

    /// Whether the client should clear the previous diagnostics
    /// mapped to the same `textDocument` and `buildTarget`.
    var reset: Bool
}
